name: "[Job] Azure Terraform Apply"

on:
  workflow_call:
    inputs:
      workspace_name:
        description: 'The terraform workspace to target for environment actions'
        required: true
        type: string
    secrets:
      arm_client_id:
        description: 'Azure ARM Client ID'
        required: true
      arm_client_secret:
        description: 'Azure ARM Client Secret'
        required: true
      arm_tenant_id:
        description: 'ARM Tenant ID'
        required: true
      arm_subscription_id:
        description: 'ARM Subscription ID'
        required: true
      workspace_client_id:
        description: 'Azure ARM Client ID for TF Workspace'
        required: true
      workspace_client_secret:
        description: 'Azure ARM Client Secret for TF Workspace'
        required: true
      workspace_tenant_id:
        description: 'ARM Tenant ID for TF Workspace'
        required: true
      workspace_subscription_id:
        description: 'ARM Subscription ID for TF Workspace'
        required: true
      github_access_token:
        description: 'Github Token'
        required: true

permissions:
  pull-requests: write
  issues: write
  id-token: write
  contents: read

jobs:
  terraform_apply_workflow:
    environment: ${{ inputs.workspace_name }}
    name: "${{ inputs.workspace_name }} deployment"
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.arm_client_id }}
      ARM_CLIENT_SECRET: ${{ secrets.arm_client_secret }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.arm_subscription_id }}
      ARM_TENANT_ID: ${{ secrets.arm_tenant_id }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
        
      - name: Terraform Init
        run: terraform init -input=false
        env:
          TF_WORKSPACE: ${{ inputs.workspace_name }}
          TF_VAR_workspace_name: ${{ inputs.workspace_name }}
          TF_VAR_subscription_id: ${{ secrets.workspace_subscription_id }}
          TF_VAR_tenant_id: ${{ secrets.workspace_tenant_id }}
          TF_VAR_client_id: ${{ secrets.workspace_client_id }}
          TF_VAR_client_secret: ${{ secrets.workspace_client_secret }}
          TF_VAR_idam_email_recipient: ${{ vars.idam_email_recipient }}
          TF_VAR_idam_email_sender: ${{ vars.idam_email_sender }}
        working-directory: ./terraform

      - name: Terraform Plan
        id: terraform_plan
        env:
          TF_WORKSPACE: ${{ inputs.workspace_name }}
          TF_VAR_workspace_name: ${{ inputs.workspace_name }}
          TF_VAR_subscription_id: ${{ secrets.workspace_subscription_id }}
          TF_VAR_tenant_id: ${{ secrets.workspace_tenant_id }}
          TF_VAR_client_id: ${{ secrets.workspace_client_id }}
          TF_VAR_client_secret: ${{ secrets.workspace_client_secret }}
          TF_VAR_idam_email_recipient: ${{ vars.idam_email_recipient }}
          TF_VAR_idam_email_sender: ${{ vars.idam_email_sender }}
        run: |
          terraform plan -lock-timeout=300s -input=false
        working-directory: ./terraform

      - name: Terraform Apply
        id: terraform_apply
        env:
          TF_WORKSPACE: ${{ inputs.workspace_name }}
          TF_VAR_workspace_name: ${{ inputs.workspace_name }}
          TF_VAR_subscription_id: ${{ secrets.workspace_subscription_id }}
          TF_VAR_tenant_id: ${{ secrets.workspace_tenant_id }}
          TF_VAR_client_id: ${{ secrets.workspace_client_id }}
          TF_VAR_client_secret: ${{ secrets.workspace_client_secret }}
          TF_VAR_idam_email_recipient: ${{ vars.idam_email_recipient }}
          TF_VAR_idam_email_sender: ${{ vars.idam_email_sender }}
        run: |
          terraform apply -lock-timeout=300s -input=false -auto-approve -parallelism=30 
        working-directory: ./terraform
